// This file is automatically generated or modified.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// FALLBACK REGISTRY (Bypass build-time stripping)
const SUPABASE_URL = (window as any).SUPABASE_URL || "https://psvbnkdbcqlqbffchkec.supabase.co";
const SUPABASE_ANON_KEY = (window as any).SUPABASE_ANON_KEY || "sb_publishable_0bbOrKvCnsy2zXBNQ-mLkg_MKRJ9nNl";

console.log("Supabase Client: Initializing credentials.");

const isDefaultOrPlaceholder = 
  !SUPABASE_URL || 
  SUPABASE_URL.includes("psvbnkdbcqlqbffchkec") || 
  SUPABASE_URL.includes("gtjgfefzexepzektbxjl") ||
  localStorage.getItem("use_mock_supabase") === "true";

// Setup global auth and database listener arrays for mocking
const authListeners = new Set<(event: string, session: any) => void>();
const dbListeners = new Set<() => void>();

function notifyAuthStateChange(event: string, session: any) {
  authListeners.forEach(listener => {
    try {
      listener(event, session);
    } catch (e) {
      console.error("Auth listener error:", e);
    }
  });
}

function notifyDbChange() {
  dbListeners.forEach(listener => {
    try {
      listener();
    } catch (e) {
      console.error("DB listener error:", e);
    }
  });
}

class MockQueryBuilder {
  tableName: string;
  data: any[] = [];
  filters: ((item: any) => boolean)[] = [];
  orderByField: string | null = null;
  orderByAscending = true;
  operation: "select" | "insert" | "update" | "delete" = "select";
  insertPayload: any[] = [];
  updatePayload: any = null;

  constructor(tableName: string) {
    this.tableName = tableName;
    if (tableName === "patients") {
      const saved = localStorage.getItem("mock_supabase_patients");
      this.data = saved ? JSON.parse(saved) : [];
      if (this.data.length === 0) {
        // Pre-populate with standard sample data so the dashboard is not completely blank initially
        this.data = [
          {
            id: "patient-1",
            name: "John Doe",
            severity: "Moderate",
            needs_icu: false,
            assigned_bed: "Normal",
            bed_number: "N-1",
            floor_number: 2,
            oxygen_level: 97,
            heart_rate: 72,
            created_at: new Date(Date.now() - 3600000).toISOString(),
            status: "Confirmed"
          },
          {
            id: "patient-2",
            name: "Jane Smith",
            severity: "Critical",
            needs_icu: true,
            assigned_bed: "ICU",
            bed_number: "ICU-1",
            floor_number: 1,
            oxygen_level: 89,
            heart_rate: 104,
            created_at: new Date(Date.now() - 1800000).toISOString(),
            status: "Confirmed"
          },
          {
            id: "patient-3",
            name: "Alice Johnson",
            severity: "Low",
            needs_icu: false,
            assigned_bed: "Waiting",
            bed_number: null,
            floor_number: null,
            oxygen_level: 98,
            heart_rate: 68,
            created_at: new Date().toISOString(),
            status: "Waiting"
          }
        ];
        localStorage.setItem("mock_supabase_patients", JSON.stringify(this.data));
      }
    }
  }

  save() {
    if (this.tableName === "patients") {
      localStorage.setItem("mock_supabase_patients", JSON.stringify(this.data));
      notifyDbChange();
    }
  }

  select(fields?: string) {
    // Keep operation as insert/update/delete if already set
    if (this.operation === "select") {
      this.operation = "select";
    }
    return this;
  }

  order(field: string, options?: { ascending: boolean }) {
    this.orderByField = field;
    this.orderByAscending = options?.ascending !== false;
    return this;
  }

  eq(field: string, value: any) {
    this.filters.push(item => item[field] === value);
    return this;
  }

  neq(field: string, value: any) {
    this.filters.push(item => item[field] !== value);
    return this;
  }

  ilike(field: string, pattern: string) {
    const regexStr = pattern.replace(/%/g, ".*");
    const regex = new RegExp(`^${regexStr}$`, "i");
    this.filters.push(item => regex.test(item[field] || ""));
    return this;
  }

  insert(array: any[]) {
    this.operation = "insert";
    this.insertPayload = array;
    return this;
  }

  update(fields: any) {
    this.operation = "update";
    this.updatePayload = fields;
    return this;
  }

  delete() {
    this.operation = "delete";
    return this;
  }

  async execute() {
    if (this.operation === "insert") {
      const insertedItems = this.insertPayload.map(item => {
        const newItem = {
          id: item.id || crypto.randomUUID(),
          created_at: new Date().toISOString(),
          oxygen_level: item.oxygen_level !== undefined ? item.oxygen_level : 95,
          heart_rate: item.heart_rate !== undefined ? item.heart_rate : 75,
          needs_icu: item.needs_icu !== undefined ? item.needs_icu : false,
          assigned_bed: item.assigned_bed || "Waiting",
          bed_number: item.bed_number || null,
          floor_number: item.floor_number || null,
          status: item.status || "Waiting",
          ...item
        };
        this.data.push(newItem);
        return newItem;
      });
      this.save();
      return { data: insertedItems, error: null };
    }

    let filtered = [...this.data];
    for (const filter of this.filters) {
      filtered = filtered.filter(filter);
    }

    if (this.operation === "select") {
      if (this.orderByField) {
        const field = this.orderByField;
        const asc = this.orderByAscending;
        filtered.sort((a, b) => {
          const valA = a[field];
          const valB = b[field];
          if (valA < valB) return asc ? -1 : 1;
          if (valA > valB) return asc ? 1 : -1;
          return 0;
        });
      }
      return { data: filtered, error: null };
    }

    if (this.operation === "update") {
      const idsToUpdate = new Set(filtered.map(r => r.id));
      this.data = this.data.map(item => {
        if (idsToUpdate.has(item.id)) {
          return { ...item, ...this.updatePayload };
        }
        return item;
      });
      this.save();
      return { data: null, error: null };
    }

    if (this.operation === "delete") {
      const idsToDelete = new Set(filtered.map(r => r.id));
      this.data = this.data.filter(item => !idsToDelete.has(item.id));
      this.save();
      return { data: null, error: null };
    }

    return { data: null, error: { message: "Invalid operation" } };
  }

  // Support direct await on this builder (thenable)
  async then(resolve: any, reject: any) {
    try {
      const res = await this.execute();
      resolve(res);
    } catch (e) {
      if (reject) reject(e);
    }
  }

  // Support single()
  async single() {
    const { data, error } = await this.execute();
    if (error) return { data: null, error };
    if (!data || (Array.isArray(data) && data.length === 0)) {
      return { data: null, error: { message: "No row found" } };
    }
    return { data: Array.isArray(data) ? data[0] : data, error: null };
  }
}

const mockAuth = {
  async getSession() {
    try {
      const sessionStr = localStorage.getItem("mock_supabase_session");
      const session = sessionStr ? JSON.parse(sessionStr) : null;
      return { data: { session }, error: null };
    } catch (e) {
      return { data: { session: null }, error: e };
    }
  },

  async signInWithPassword({ email, password }: any) {
    try {
      const usersStr = localStorage.getItem("mock_supabase_users");
      const users = usersStr ? JSON.parse(usersStr) : [];
      const user = users.find((u: any) => u.email === email && u.password === password);

      if (!user) {
        return { data: { user: null, session: null }, error: { message: "Invalid login credentials" } };
      }

      const session = {
        user: { id: user.id, email: user.email },
        access_token: "mock-jwt-token",
        expires_at: Math.floor(Date.now() / 1000) + 3600
      };

      localStorage.setItem("mock_supabase_session", JSON.stringify(session));
      notifyAuthStateChange("SIGNED_IN", session);
      return { data: { user: session.user, session }, error: null };
    } catch (e: any) {
      return { data: { user: null, session: null }, error: { message: e.message } };
    }
  },

  async signUp({ email, password }: any) {
    try {
      const usersStr = localStorage.getItem("mock_supabase_users");
      const users = usersStr ? JSON.parse(usersStr) : [];

      if (users.some((u: any) => u.email === email)) {
        return { data: { user: null, session: null }, error: { message: "User already exists" } };
      }

      const newUser = { id: crypto.randomUUID(), email, password };
      users.push(newUser);
      localStorage.setItem("mock_supabase_users", JSON.stringify(users));

      const session = {
        user: { id: newUser.id, email: newUser.email },
        access_token: "mock-jwt-token",
        expires_at: Math.floor(Date.now() / 1000) + 3600
      };

      localStorage.setItem("mock_supabase_session", JSON.stringify(session));
      notifyAuthStateChange("SIGNED_IN", session);
      return { data: { user: session.user, session }, error: null };
    } catch (e: any) {
      return { data: { user: null, session: null }, error: { message: e.message } };
    }
  },

  async signOut() {
    localStorage.removeItem("mock_supabase_session");
    notifyAuthStateChange("SIGNED_OUT", null);
    return { error: null };
  },

  onAuthStateChange(callback: any) {
    authListeners.add(callback);

    // Call callback immediately with current session
    const sessionStr = localStorage.getItem("mock_supabase_session");
    let session = null;
    try {
      session = sessionStr ? JSON.parse(sessionStr) : null;
    } catch (e) {
      console.error("Failed to parse session on onAuthStateChange init", e);
    }
    
    setTimeout(() => {
      try {
        callback("INITIAL_SESSION", session);
      } catch (e) {
        console.error("Initial session callback error:", e);
      }
    }, 0);

    return {
      data: {
        subscription: {
          unsubscribe() {
            authListeners.delete(callback);
          }
        }
      }
    };
  }
};

const createMockSupabaseClient = () => {
  return {
    isMock: true,
    auth: mockAuth,
    from(tableName: string) {
      return new MockQueryBuilder(tableName);
    },
    channel(name: string) {
      return {
        on(event: string, filter: any, callback: any) {
          const dbListener = () => {
            // Trigger with a mock event payload
            callback({ eventType: "INSERT", new: { assigned_bed: "Waiting" } });
          };
          dbListeners.add(dbListener);
          (this as any)._listener = dbListener;
          return this;
        },
        subscribe() {
          return this;
        }
      };
    },
    removeChannel(channel: any) {
      if (channel && channel._listener) {
        dbListeners.delete(channel._listener);
      }
    }
  } as any;
};

// Initialize the appropriate client
export const supabase = isDefaultOrPlaceholder
  ? (() => {
      console.warn("⚠️ Utilizing local Mock Supabase client fallback (offline mode).");
      return createMockSupabaseClient();
    })()
  : (SUPABASE_URL && SUPABASE_ANON_KEY)
    ? createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        }
      })
    : (() => {
        console.warn("⚠️ No Supabase credentials found. Falling back to local Mock client.");
        return createMockSupabaseClient();
      })();