// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// FALLBACK REGISTRY (Bypass build-time stripping)
const SUPABASE_URL = (window as any).SUPABASE_URL || "https://psvbnkdbcqlqbffchkec.supabase.co";
const SUPABASE_ANON_KEY = (window as any).SUPABASE_ANON_KEY || "sb_publishable_0bbOrKvCnsy2zXBNQ-mLkg_MKRJ9nNl";

console.log("Supabase Client: Initializing with Global/Hardcoded credentials.");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = (SUPABASE_URL && SUPABASE_ANON_KEY) 
  ? createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : null as any; // Fallback to null instead of crashing during evaluation